### ISSUE TITLE
Error: Cannot find module 'tslib'

### ISSUE THREAD

**Issue by elishnevsky** [UltimateAngular/aot-loader#3]
**Is this a feature request or a bug report?**
Bug

**What's gone wrong?**
Error during compilation

**Other information**
My first attempt to use the loader was unsuccessful. I configured everything as described in wiki and I'm getting the following error: 
```
module.js:471
    throw err;
    ^

Error: Cannot find module 'tslib'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at MagicString (C:\Development\Temp\angular-aot\node_modules\@ultimate\aot-loader\bundle\ultimate.aot.umd.js:2:85)

    at Object.<anonymous> (C:\Development\Temp\angular-aot\node_modules\@ultimate\aot-loader\bundle\ultimate.aot.umd.js:5:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```
Windows 10 x64
Node v6.9.5
NPM v4.2.0

I've created a test repo here: https://github.com/elishnevsky/aot-loader-test

Let me know if you need more information.

Thank you,
Eugene.

**Comment by elishnevsky** [comment]
I've made some progress. First, I manually installed tslib (should be done for me, in my opinion), and fixed the path to tsconfig.json (used wrong property name).

Now it compiles, but I'm getting the following warnings:
```
WARNING in ../~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
71:15-36 Critical dependency: the request of a dependency is an expression

WARNING in ../~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
87:15-102 Critical dependency: the request of a dependency is an expression
```
I remember these warnings from before. They are related to this issue: https://github.com/angular/angular/issues/11580

After adding ContextReplacementPlugin to the plugins, the warnings went away. Just an FYI. Perhaps you can do something about them.

**Comment by rynclark** [comment]
Oops! Should be all fixed now in `0.1.4`.

Regarding the `Critical dependency: the request of a dependency is an expression` error - I've had this appear before but can't remember the steps I did to get rid of it, but I'm not getting it at all on any test projects or tests, and using the `ContextReplacementPlugin` wasn't the solution.

If I remember what it was I'll let you know, if you are still getting it could you possibly send me your code base so I can try to reproduce?

Cheers!

**Comment by elishnevsky** [comment]
You can check out my [test repo](https://github.com/elishnevsky/aot-loader-test). I have to use the `ContextReplacementPlugin` in the webpack.config.js to get rid of the warnings. If I comment it out, I start getting them.

**Comment by rynclark** [comment]
@elishnevsky the only possible reason I can think of after doing a bit of investigation is that I'm using the 4.0.0-beta and you're using 2.4.8 - they could have possibly fixed this between the two versions.

It isn't an error exactly, it's just because there is code that uses `System.import` with a variable in the Angular core - nothing to worry about.

**Comment by elishnevsky** [comment]
@rynclark I'm still getting these warnings even with the latest beta (4.0.0-beta.8 at the moment). I'm not too worried. After all they are just warnings. Thanks for looking into this anyways.
